import argparse
import datetime
import os
import sys

import xarray as xr

sys.path.insert(0, os.path.abspath('.'))

from Base import getInnerBoxMask
from Utilities import downloadRdaCONUS404
from Preprocess.Model import PreprocessWRF
from TempestExtremes import (
    CONUS404InputName, TempestExtremes, MCSClassifier, 
    BlobStatsParallelization)
from System import defineScratch

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=('USTORM (Unified Storm Tracking for Observations and '
        'multi-Resolution Models) mesoscale convective system tracking and classification '
        'workflow script for CONUS404.'))
    parser.add_argument(
        '--begin', action='store', metavar='%YYYY%mm%dd_%H',
        required=True,
        help='The beginning of the calculation period.'
    )
    parser.add_argument(
        '--end', action='store', metavar='%YYYY%mm%dd_%H',
        required=True,
        help='The end of the calculation period.'
    )
    parser.add_argument(
        '--step', action='store', metavar='Hour',
        type=int, default=1,
        help='Time step of the data.'
    )
    parser.add_argument(
        '--te_path', '-te', action='store', metavar='TempestExtremesPath',
        default='',
        help='Path to tempestextremes bin directory.'
    )
    parser.add_argument(
        '--mpirun', '-mpi', action='store', metavar='MPIPath',
        default=None,
        help='Path to MPI launch program (e.g., mpirun or mpiexec).'
    )
    parser.add_argument(
        '--mpi_arg', action='store', metavar='MPIArg',
        default=None,
        help=('Arguments of the MPI launch program. '
              'For example, use \"-np N\" to run tempestextremes with N cores')
    )
    parser.add_argument(
        '--work_dir', action='store', metavar='WorkDir',
        default=None,
        help=('The work directory used to store results. '
              'Default: directory TempestExtremes under your scratch '
              'or home directory')
    )
    parser.add_argument(
        '--lps_file', action='store', metavar='SyCLoPS parquet output',
        type=str, default=None, 
        help=('LPS track file generated by SyCLoPS.')
    )
    parser.add_argument(
        '--lps_blob_files', action='store', metavar='Filename',
        type=str, default=None, 
        help=('A txt file containing LPS numbered blob filenames '
              'generated by StitchNodes.')
    )
    parser.add_argument(
        '--front_file', action='store', metavar='SyCLoPS parquet output',
        type=str, default=None, 
        help=('Frontal track file generated by SyCLoPS.')
    )
    parser.add_argument(
        '--frontal_blob_files', action='store', metavar='Filename',
        type=str, default=None, 
        help=('A txt file containing front numbered blob filenames '
              'generated by StitchNodes.')
    )
    parser.add_argument(
        '--data_root', '--data_dir', action='store', metavar='DataRoot',
        default=None,
        help=('The root directory that is used to download and store data. '
              'Default: WorkDir/Data.')
    )
    parser.add_argument(
        '--nproc', action='store', metavar='N',
        type=int, default=8,
        help='Number of processes.'
    )
    parser.add_argument(
        '--full_result', '--full', action='store', metavar='StoreFullResult',
        type=bool, default=False,
        help='Whether to save verbose info.'
    )
    parser.add_argument(
        '--result_format', '--format', action='store', metavar='Format',
        default='parquet',
        help=('The format of result to be stored. Supported: '
              'parquet (default), xlsx, all (i.e., parquet & xlsx)')
    )
    parser.add_argument(
        '--tb_name', action='store', metavar='Format',
        default='TB',
        help=('The variable name of brightness temperature used to track '
              'MCS. The hardcoded threshold is based on IR longwave window '
              'channel (i.e., 241 and 225K).')
    )
    parser.add_argument(
        '--rr_name', action='store', metavar='Format',
        default='PREC_ACC_NC',
        help=('The variable name of rain rate used to track MCS.')
    )
    parser.add_argument(
        '--rr_threshold', action='store', metavar='Format',
        type=float, default=2.0,
        help=('The threshold of rain rate (mm/hr) used to track MCS. '
              'If there is any grid point of the MCS candidate meets the ' \
              'threshold, then it will be considered as a MCS.')
    )
    parserArgs = parser.parse_args()
    tempestExtremesPath = vars(parserArgs).get('te_path')
    mpirunPath = vars(parserArgs).get('mpirun')
    mpiArgStr = vars(parserArgs).get('mpi_arg')
    mpiArg = mpiArgStr.replace('\"', '').replace('\'', '').split(' ') if (
        mpiArgStr is not None) else []
    
    scratchDir = defineScratch()
    workDir = vars(parserArgs).get('work_dir')
    workDir = os.path.join(scratchDir, 'TempestExtremes') if (
        workDir is None) else workDir
    dataRoot = vars(parserArgs).get('data_root')
    dataRoot = os.path.join(workDir, 'Data') if (dataRoot is None) else dataRoot
    beginTimeStr = vars(parserArgs).get('begin')
    endTimeStr = vars(parserArgs).get('end')
    lpsFile = vars(parserArgs).get('lps_file')
    lpsBlobOutput = vars(parserArgs).get('lps_blob_files')
    frontPreprocessFile = vars(parserArgs).get('front_file')
    frontBlobOutput = vars(parserArgs).get('frontal_blob_files')
    fullResult = vars(parserArgs).get('full_result')
    reusltFormat = vars(parserArgs).get('result_format')
    step = vars(parserArgs).get('step')
    nproc = vars(parserArgs).get('nproc')
    tbName = vars(parserArgs).get('tb_name')
    rainRateName = vars(parserArgs).get('rr_name')
    rainRateThreshold = vars(parserArgs).get('rr_threshold')

    # Download CONUS404 from RDA
    downloadRdaCONUS404(dataRoot, beginTimeStr, endTimeStr, step=step, override=False)

    preprocessDir = f'{workDir}/preprocess'

    tempestExtremes = TempestExtremes(tempestExtremesPath, mpirunPath, mpiArg)

    beginTime = datetime.datetime.strptime(beginTimeStr, "%Y%m%d_%H")
    endTime = datetime.datetime.strptime(endTimeStr, "%Y%m%d_%H")
    blobStatsOutput = os.path.join(workDir, 'BlobStatsOutput_MCS.txt')
    classifierPreprocessFile = os.path.join(workDir, f'Preprocess_{beginTime:%Y%m%d%H}_{endTime:%Y%m%d%H}.parquet')
    classifierFinalFile = os.path.join(workDir, f'Result_{beginTime:%Y%m%d%H}_{endTime:%Y%m%d%H}')
    inputName = CONUS404InputName(root=dataRoot, step=step)
    inputName.setDateTime(begin=beginTime, end=endTime)
    inputName.generateInput(types=['wrf3d'])
    fileList = inputName.getInputAsList()
    inputName.generateInput(types=['wrf2d'])
    wrf2dList = inputName.getInputAsList()
    # Pre-process CONUS 404
    originalInvariantPath = inputName.getInvariantPaths().get('invariant')
    preprocessor = PreprocessWRF(fileList, wrf2dFiles=wrf2dList)
    preprocessor.setInvariantPath(originalInvariantPath)
    varRaname = dict(
        lev = 'ZNU',
        ilev = 'ZNW',
    )
    varUnitChange = dict(
        Z = 'm'
    )
    varProcess = dict(
        Vo = dict(
            derivative = 'vo',
            zCoord = 'P',
            var = ['U', 'V'],
            level = [85000],
            suffix = [850],
            mapFacX = 'MAPFAC_MX',
            mapFacY = 'MAPFAC_MY',
            method = 'linear',
        ),
        TB = dict(
            derivative = 'tb_from_olr',
            var = 'OLR',
        )
        # The following setting is used for RTTOV derived brightness temperature 
        # (Bands 13 and 14).
        # C = dict(
        #     derivative = 'tb_from_rttov',
        #     lon = 'XLONG',
        #     lat = 'XLAT',
        #     terrianHeight = 'HGT',
        #     surfaceType = 'LANDMASK',
        #     channel = [13, 14],
        #     suffix = [13, 14],
        #     var = [
        #         'TK', 'P', 'QVAPOR', 'QICE', 'QSNOW', 'QCLOUD', 'CLDFRA', 
        #         'TSK', 'SNOWC', 'T2', 'Q2', 'U10', 'V10', 'ALBEDO', 'EMISS'],
        # ),
    )
    preprocessedList = preprocessor.process(varProcess, preprocessDir, requireMapFactor=False, 
                         varRename=varRaname, varUnitChange=varUnitChange,
                         nproc=nproc, override=False, fileSuffix='_MCS')

    # Detect MCSs
    inputFileName = os.path.join(workDir, 'DetectBlobsInputFilenames.txt')
    detectBlobsOutput = os.path.join(workDir, 'DetectBlobsOutputFilenames.txt')
    logRoot = os.path.join(workDir, 'log')
    if not os.path.exists(logRoot):
        os.makedirs(logRoot)
    invariantBasename = os.path.basename(originalInvariantPath)
    tmpInvariantPath = os.path.join(workDir, invariantBasename)
    if not os.path.exists(tmpInvariantPath):
        invariantDataset = xr.open_dataset(originalInvariantPath)
        invariantDataset = invariantDataset[dict(Time=0)]
        invariantDataset = invariantDataset.drop_vars('Time')
        if 'HGT' in invariantDataset.variables.keys():
            invariantDataset = invariantDataset.rename_vars({
                                                            'HGT': 'Z0'})
        innerBoxMask = getInnerBoxMask(
            invariantDataset['XLONG'].to_numpy(), 
            invariantDataset['XLAT'].to_numpy(), offset=2.0)
        invariantDataset['InnerBoxMask'] = invariantDataset['LANDMASK'].copy(
            data=innerBoxMask)
        invariantDataset.to_netcdf(tmpInvariantPath)

    with open(inputFileName, 'w') as f:
        for i,j in zip(preprocessedList, wrf2dList):
            f.write(f'{i};{j};{tmpInvariantPath}\n')
    with open(detectBlobsOutput, 'w') as f:
        currentTime = beginTime
        while currentTime <= endTime:
            currentOutputFile = os.path.join(workDir,
                                             f'DetectBlobsOutput_{currentTime:%Y%m%d_%H%M%S}.nc')
            f.write(f'{currentOutputFile}\n')
            currentTime += datetime.timedelta(hours=step)

    logDir = os.path.join(logRoot, 'DetectBlobs')
    if not os.path.exists(logDir):
        os.mkdir(logDir)
    detectBlobsArg = [
        '--in_data_list', inputFileName,
        '--out_list', detectBlobsOutput,
        '--thresholdcmd', f'{tbName},<=,241,0',
        '--filtercmd', f'{tbName},<=,225,1;{rainRateName},>=,{rainRateThreshold},1',
        '--tagvar', 'blobmask',
        '--latname', 'XLAT',
        '--lonname', 'XLONG',
        '--regional',
        '--logdir', logDir
    ]
    tempestExtremes.run('DetectBlobs', detectBlobsArg)

    stitchBlobsOutputFilename = os.path.join(workDir, 'StitchBlobsOutputFilenames.txt')
    with open(stitchBlobsOutputFilename, 'w') as f:
        currentTime = beginTime
        while currentTime <= endTime:
            currentOutputFile = os.path.join(workDir,
                                             f'StitchBlobsOutput_{currentTime:%Y%m%d_%H%M%S}.nc')
            f.write(f'{currentOutputFile}\n')
            currentTime += datetime.timedelta(hours=step)
    inputFileName = detectBlobsOutput
    outputFileName = stitchBlobsOutputFilename
    stitchBlobsArg = [
        '--in_list', inputFileName,
        '--out_list', outputFileName,
        '--var', 'blobmask',
        '--outvar', 'MCS',
        '--mintime', '6',
        '--min_overlap_next', '50.0',
        '--latname', 'XLAT',
        '--lonname', 'XLONG',
        '--regional',
        '--verbose',
    ]
    tempestExtremes.run('StitchBlobs', stitchBlobsArg)

    # Summary the information of each MCS region, which will be used 
    # in the MCS classifier.
    inputFileName = os.path.join(workDir, 'BlobStatsInputFilenames.txt')
    vorticityFileList = preprocessedList
    detectBlobsOutputList = []
    lpsBlobsOutputList = []
    frontBlobsOutputList = []
    lpsStep = 3
    with open(outputFileName, 'r') as f:
        detectBlobsOutputList = f.read().splitlines()
    with open(lpsBlobOutput, 'r') as f:
        lpsBlobsOutputList = f.read().splitlines()
    with open(frontBlobOutput, 'r') as f:
        frontBlobsOutputList = f.read().splitlines()
    with open(inputFileName, 'w') as f:
        for i, (iMcsBlob, iVort) in enumerate(
                zip(detectBlobsOutputList, vorticityFileList)):
            if i % lpsStep == 0:
                iLpsCounter = i // lpsStep
                f.write(f'{iMcsBlob};{iVort}')
                f.write(f';{lpsBlobsOutputList[iLpsCounter]};{frontBlobsOutputList[iLpsCounter]}\n')

    outputFileName = blobStatsOutput
    blobStatsArg = [
        '--var', 'MCS',
        '--out', 'centlon,centlat,minlat,maxlat,minlon,maxlon,area',
        '--latname', 'XLAT',
        '--lonname', 'XLONG',
        '--timefilter', '3hr',
        '--out_fulltime',
        # Vorticity at 850hPa
        '--sumvar', 'Vo850',
        '--overlapvar', 'GradientMask,FrontalMask',
        '--regional'
    ]
    blobStatsParallelization = BlobStatsParallelization(
        tempestExtremes, inputFileName, blobStatsArg)
    blobStatsParallelization.run(outputFileName, nproc=nproc)

    if lpsFile is not None and lpsBlobOutput is not None:
        mcsClassifier = MCSClassifier(
            blobStatsOutput, lpsFile, tmpInvariantPath, 
            lonName='XLONG', latName='XLAT', regional=True, nproc=nproc,
            frontProcessedOutput=frontPreprocessFile,
            rhTropicalThreshold=17)
        mcsClassifier.preprocess(classifierPreprocessFile, override=True)
