import argparse
import datetime
import os
import sys

import numpy as np
from scipy import spatial
import xarray as xr

sys.path.insert(0, os.path.abspath('.'))

from Base import getBoxMask
from Utilities import downloadGesDiscMergedIR, downloadRdaIMERG
from Preprocess.Model import PreprocessERA5
from Preprocess.Observation import PreprocessIMERG
from TempestExtremes import (
    ERA5InputName, IMERGInputName, TempestExtremes, MCSClassifier, 
    BlobStatsParallelization)
from System import defineScratch

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=('USTORM (Unified Storm Tracking for Observations and '
        'multi-Resolution Models) mesoscale convective system tracking and classification '
        'workflow script for IMERG.'))
    parser.add_argument(
        '--begin', action='store', metavar='%YYYY%mm%dd_%H',
        required=True,
        help='The beginning of the calculation period.'
    )
    parser.add_argument(
        '--end', action='store', metavar='%YYYY%mm%dd_%H',
        required=True,
        help='The end of the calculation period.'
    )
    parser.add_argument(
        '--step', action='store', metavar='Hour',
        type=int, default=1,
        help='Time step of the data.'
    )
    parser.add_argument(
        '--te_path', '-te', action='store', metavar='TempestExtremesPath',
        default='',
        help='Path to tempestextremes bin directory.'
    )
    parser.add_argument(
        '--mpirun', '-mpi', action='store', metavar='MPIPath',
        default=None,
        help='Path to MPI launch program (e.g., mpirun or mpiexec).'
    )
    parser.add_argument(
        '--mpi_arg', action='store', metavar='MPIArg',
        default=None,
        help=('Arguments of the MPI launch program. '
              'For example, use \"-np N\" to run tempestextremes with N cores')
    )
    parser.add_argument(
        '--work_dir', action='store', metavar='WorkDir',
        default=None,
        help=('The work directory used to store results. '
              'Default: directory TempestExtremes under your scratch '
              'or home directory')
    )
    parser.add_argument(
        '--regional_mask_file', action='store', metavar='RegionalFile',
        default=None,
        help=('A file with regional domain information.')
    )
    parser.add_argument(
        '--regional_mask_variable', action='store', metavar='RegionalMaskVar',
        default='RegionalMask',
        help=('The regional mask variable name.')
    )
    parser.add_argument(
        '--lps_file', action='store', metavar='SyCLoPS parquet output',
        type=str, default=None, 
        help=('LPS track file generated by SyCLoPS.')
    )
    parser.add_argument(
        '--lps_blob_files', action='store', metavar='Filename',
        type=str, default=None, 
        help=('A txt file containing LPS numbered blob filenames '
              'generated by StitchNodes.')
    )
    parser.add_argument(
        '--front_file', action='store', metavar='SyCLoPS parquet output',
        type=str, default=None, 
        help=('Frontal track file generated by SyCLoPS.')
    )
    parser.add_argument(
        '--frontal_blob_files', action='store', metavar='Filename',
        type=str, default=None, 
        help=('A txt file containing front numbered blob filenames '
              'generated by StitchNodes.')
    )
    parser.add_argument(
        '--data_root_IMERG', '--data_dir_IMERG', action='store', metavar='DataRootIMERG',
        default=None,
        help=('The root directory that is used to download and store data. '
              'Default: WorkDir/Data.')
    )
    parser.add_argument(
        '--data_root_IR', '--data_dir_IR', action='store', metavar='DataRootIR',
        default=None,
        help=('The root directory that is used to download and store data. '
              'Default: WorkDir/Data.')
    )
    parser.add_argument(
        '--data_root_ERA', '--data_dir_ERA', action='store', metavar='DataRootERA',
        default=None,
        help=('The root directory that is used to download and store data. '
              'Default: WorkDir/Data.')
    )
    parser.add_argument(
        '--nproc', action='store', metavar='N',
        type=int, default=8,
        help='Number of processes.'
    )
    parser.add_argument(
        '--full_result', '--full', action='store', metavar='StoreFullResult',
        type=bool, default=False,
        help='Whether to save verbose info.'
    )
    parser.add_argument(
        '--result_format', '--format', action='store', metavar='Format',
        default='parquet',
        help=('The format of result to be stored. Supported: '
              'parquet (default), xlsx, all (i.e., parquet & xlsx)')
    )
    parser.add_argument(
        '--tb_name', action='store', metavar='Format',
        default='Tb',
        help=('The variable name of brightness temperature used to track '
              'MCS. The hardcoded threshold is based on IR longwave window '
              'channel (i.e., 241 and 225K).')
    )
    parser.add_argument(
        '--rr_name', action='store', metavar='Format',
        default='precipitation',
        help=('The variable name of rain rate used to track MCS.')
    )
    parser.add_argument(
        '--rr_threshold', action='store', metavar='Format',
        type=float, default=2.0,
        help=('The threshold of rain rate (mm/hr) used to track MCS. '
              'If there is any grid point of the MCS candidate meets the ' \
              'threshold, then it will be considered as a MCS.')
    )
    parserArgs = parser.parse_args()
    tempestExtremesPath = vars(parserArgs).get('te_path')
    mpirunPath = vars(parserArgs).get('mpirun')
    mpiArgStr = vars(parserArgs).get('mpi_arg')
    mpiArg = mpiArgStr.replace('\"', '').replace('\'', '').split(' ') if (
        mpiArgStr is not None) else []
    
    scratchDir = defineScratch()
    workDir = vars(parserArgs).get('work_dir')
    workDir = os.path.join(scratchDir, 'TempestExtremes') if (
        workDir is None) else workDir
    dataRootIMERG = vars(parserArgs).get('data_root_IMERG')
    dataRootIMERG = os.path.join(workDir, 'Data') if (dataRootIMERG is None) else dataRootIMERG
    dataRootIR = vars(parserArgs).get('data_root_IR')
    dataRootIR = dataRootIMERG if (dataRootIR is None) else dataRootIR
    dataRootERA = vars(parserArgs).get('data_root_ERA')
    dataRootERA = dataRootIMERG if (dataRootERA is None) else dataRootERA
    beginTimeStr = vars(parserArgs).get('begin')
    endTimeStr = vars(parserArgs).get('end')
    regionalMaskFilename = vars(parserArgs).get('regional_mask_file')
    regionalMaskVar = vars(parserArgs).get('regional_mask_variable')
    lpsFile = vars(parserArgs).get('lps_file')
    lpsBlobOutput = vars(parserArgs).get('lps_blob_files')
    frontPreprocessFile = vars(parserArgs).get('front_file')
    frontBlobOutput = vars(parserArgs).get('frontal_blob_files')
    fullResult = vars(parserArgs).get('full_result')
    reusltFormat = vars(parserArgs).get('result_format')
    step = vars(parserArgs).get('step')
    nproc = vars(parserArgs).get('nproc')
    tbName = vars(parserArgs).get('tb_name')
    rainRateName = vars(parserArgs).get('rr_name')
    rainRateThreshold = vars(parserArgs).get('rr_threshold')
    flagRegional = True if regionalMaskFilename is not None else False

    # Download IMERG from NCAR RDA and Merged IR from NASA GES DISC
    downloadRdaIMERG(dataRootIMERG, beginTimeStr, endTimeStr, step=step, override=False)
    downloadGesDiscMergedIR(dataRootIR, beginTimeStr, endTimeStr, step=step, override=False)

    beginTime = datetime.datetime.strptime(beginTimeStr, "%Y%m%d_%H")
    endTime = datetime.datetime.strptime(endTimeStr, "%Y%m%d_%H")
    dataRootMapping = dict(
        IMERG=dataRootIMERG,
        MergedIR=dataRootIR
    )
    inputName = IMERGInputName(root=dataRootMapping, step=step)
    inputName.setDateTime(begin=beginTime, end=endTime)
    inputName.generateInput(types=['IMERG'])
    inputNameERA5 = ERA5InputName(root=dataRootERA)
    inputNameERA5.setDateTime(begin=beginTime, end=endTime)
    mlSpFiles = inputNameERA5.generateInput(
        ['128_134_sp.regn320sc'], output=True, step=6).splitlines()
    mlTFiles = inputNameERA5.generateInput(
        ['0_5_0_0_0_t.regn320sc'], output=True, step=6).splitlines()
    mlQFiles = inputNameERA5.generateInput(
        ['0_5_0_1_0_q.regn320sc'], output=True, step=6).splitlines()
    mlUFiles = inputNameERA5.generateInput(
        ['0_5_0_2_2_u.regn320uv'], output=True, step=6).splitlines()
    mlVFiles = inputNameERA5.generateInput(
        ['0_5_0_2_3_v.regn320uv'], output=True, step=6).splitlines()
    processorERA5 = PreprocessERA5(
        mlSpFiles, mlTFiles, mlQFiles, mlUFiles, mlVFiles)
    fileListIMERG = inputName.getInputAsList()
    inputName.generateInput(types=['MergedIR'])
    fileListMergedIR = inputName.getInputAsList()

    varProcessIMERG = dict(
        precipitation = dict(
            var = 'precipitation',
            method = 'mean',
            transpose = ["time", "lat", "lon"],
        ),
    )
    varProcessMergedIR = dict(
        Tb = dict(
            var = 'Tb',
            time = 0,
        ),
    )

    tempestExtremes = TempestExtremes(tempestExtremesPath, mpirunPath, mpiArg)

    blobStatsOutput = os.path.join(workDir, 'BlobStatsOutput_MCS.txt')
    classifierPreprocessFile = os.path.join(workDir, f'Preprocess_{beginTime:%Y%m%d%H}_{endTime:%Y%m%d%H}.parquet')
    classifierFinalFile = os.path.join(workDir, f'Result_{beginTime:%Y%m%d%H}_{endTime:%Y%m%d%H}')

    # Pre-process IMERG
    # If preprocessed files have existed, add nameOnly=True to reduce elapsed time.
    preprocessDir = f'{workDir}/preprocess'
    processor = PreprocessIMERG(fileListIMERG, fileListMergedIR, filePerHour=2)
    preprocessedListIMERG = processor.process(
        varProcessIMERG, preprocessDir, override=False, nproc=nproc)
    preprocessedListMergedIR = processor.process(
        varProcessMergedIR, preprocessDir, override=False, 
        fileSuffix='MergedIR.IMERG', nproc=nproc)
    
    # Detect MCSs
    inputFileName = os.path.join(workDir, 'DetectBlobsInputFilenames.txt')
    detectBlobsOutput = os.path.join(workDir, 'DetectBlobsOutputFilenames.txt')
    logRoot = os.path.join(workDir, 'log')
    if not os.path.exists(logRoot):
        os.makedirs(logRoot)

    regionalMaskInvariantFile = None
    if regionalMaskFilename is not None:
        maskInvariantDs = xr.open_dataset(regionalMaskFilename)
        regionalMaskBasename = os.path.basename(regionalMaskFilename)
        regionalMaskFilenameIMERG = os.path.join(workDir, regionalMaskBasename)
        regionalMaskFilenameIMERG = regionalMaskFilenameIMERG.rsplit('.', 1)
        regionalMaskFilenameIMERG = f'{regionalMaskFilenameIMERG[0]}.IMERG.{regionalMaskFilenameIMERG[1]}'
        dsIMERG = xr.open_dataset(preprocessedListIMERG[0])
        dsRegionalMask = xr.Dataset()
        dsRegionalMask[regionalMaskVar] = dsIMERG['precipitation'].isel(time=0).copy(
            data=getBoxMask(
                dsIMERG['lon'].to_numpy(), dsIMERG['lat'].to_numpy(), 
                maskInvariantDs['XLONG'].to_numpy(), maskInvariantDs['XLAT'].to_numpy(), 
                offset=0.06))
        dsRegionalMask.to_netcdf(regionalMaskFilenameIMERG)
        inputName.addInvariantPath('mask.imerg', regionalMaskFilenameIMERG)
        regionalMaskInvariantFile = regionalMaskFilenameIMERG

    with open(inputFileName, 'w') as f:
        for i,j in zip(preprocessedListMergedIR, preprocessedListIMERG):
            f.write(f'{i};{j}')
            if regionalMaskInvariantFile is not None:
                f.write(f';{regionalMaskInvariantFile}')
            f.write('\n')
    with open(detectBlobsOutput, 'w') as f:
        currentTime = beginTime
        while currentTime <= endTime:
            currentOutputFile = os.path.join(workDir,
                                             f'DetectBlobsOutput_{currentTime:%Y%m%d_%H%M%S}.nc')
            f.write(f'{currentOutputFile}\n')
            currentTime += datetime.timedelta(hours=step)

    logDir = os.path.join(logRoot, 'DetectBlobs')
    if not os.path.exists(logDir):
        os.mkdir(logDir)
    detectBlobsThresholdCmd = f'{tbName},<=,241,0'
    if regionalMaskInvariantFile is not None:
        detectBlobsThresholdCmd += f';{regionalMaskVar},>=,1,0'
    detectBlobsArg = [
        '--in_data_list', inputFileName,
        '--out_list', detectBlobsOutput,
        '--thresholdcmd', f'{detectBlobsThresholdCmd}',
        '--filtercmd', f'{tbName},<=,225,1;{rainRateName},>=,{rainRateThreshold},1',
        '--tagvar', 'blobmask',
        '--latname', 'lat',
        '--lonname', 'lon',
        '--logdir', logDir
    ]
    tempestExtremes.run('DetectBlobs', detectBlobsArg)

    stitchBlobsOutputFilename = os.path.join(workDir, 'StitchBlobsOutputFilenames.txt')
    with open(stitchBlobsOutputFilename, 'w') as f:
        currentTime = beginTime
        while currentTime <= endTime:
            currentOutputFile = os.path.join(workDir,
                                             f'StitchBlobsOutput_{currentTime:%Y%m%d_%H%M%S}.nc')
            f.write(f'{currentOutputFile}\n')
            currentTime += datetime.timedelta(hours=step)
    inputFileName = detectBlobsOutput
    outputFileName = stitchBlobsOutputFilename
    stitchBlobsArg = [
        '--in_list', inputFileName,
        '--out_list', outputFileName,
        '--var', 'blobmask',
        '--outvar', 'MCS',
        '--mintime', '6',
        '--min_overlap_next', '50.0',
        '--latname', 'lat',
        '--lonname', 'lon',
        '--verbose',
    ]
    tempestExtremes.run('StitchBlobs', stitchBlobsArg)

    # Summary the information of each MCS region, which will be used 
    # in the MCS classifier.
    inputFileName = os.path.join(workDir, 'BlobStatsInputFilenames.txt')
    inputNameERA5.generateInput(['128_138_vo.ll025sc'])
    vorticityFileList = inputNameERA5.getInputAsList()
    detectBlobsOutputList = []
    lpsBlobsOutputList = []
    frontBlobsOutputList = []
    lpsStep = 3
    with open(outputFileName, 'r') as f:
        detectBlobsOutputList = f.read().splitlines()
    with open(lpsBlobOutput, 'r') as f:
        lpsBlobsOutputList = f.read().splitlines()
    with open(frontBlobOutput, 'r') as f:
        frontBlobsOutputList = f.read().splitlines()
    
    detectBlobsOutputList = processorERA5.regrid(
        workDir, detectBlobsOutputList, vorticityFileList[0], 'nearest_s2d', 
        fileSuffix='ll025sc', regridderSuffix='MCS.ll025sc', nproc=nproc)
    lpsBlobsOutputList = processorERA5.regrid(
        workDir, lpsBlobsOutputList, vorticityFileList[0], 'nearest_s2d', 
        fileSuffix='ll025sc',
        regridderSuffix='LPSBlob.ll025sc', nproc=nproc)
    frontBlobsOutputList = processorERA5.regrid(
        workDir, frontBlobsOutputList, vorticityFileList[0], 'nearest_s2d', 
        fileSuffix='ll025sc',
        regridderSuffix='FrontalBlob.ll025sc', nproc=nproc)
    with open(inputFileName, 'w') as f:
        for i, iMcsBlob in enumerate(detectBlobsOutputList):
            if i % lpsStep == 0:
                iERA5MLCounter = i // 6
                iERA5PLCounter = i // 24
                f.write(f'{iMcsBlob};{vorticityFileList[iERA5PLCounter]}')
                f.write(f';{lpsBlobsOutputList[iERA5MLCounter]};{frontBlobsOutputList[iERA5MLCounter]}\n')

    outputFileName = blobStatsOutput
    blobStatsArg = [
        '--var', 'MCS',
        '--out', 'centlon,centlat,minlat,maxlat,minlon,maxlon,area',
        '--latname', 'latitude',
        '--lonname', 'longitude',
        '--timefilter', '3hr',
        '--out_fulltime',
        # Vorticity at 850hPa
        '--sumvar', 'VO(850hPa)',
        '--overlapvar', 'GradientMask,FrontalMask',
    ]
    blobStatsParallelization = BlobStatsParallelization(
        tempestExtremes, inputFileName, blobStatsArg)
    blobStatsParallelization.run(outputFileName, nproc=nproc)

    if lpsFile is not None and lpsBlobOutput is not None:
        mcsClassifier = MCSClassifier(
            blobStatsOutput, lpsFile, regionalMaskFilename, 
            lonName='XLONG', latName='XLAT', regional=flagRegional, nproc=nproc,
            frontProcessedOutput=frontPreprocessFile)
        mcsClassifier.preprocess(classifierPreprocessFile, override=True)


